openapi: 3.0.3
info:
  title: URL Shortener API
  description: Сервис для сокращения URL-адресов
  version: 1.0.0
servers:
  - url: http://localhost:8080

paths:
  /api/v1/shorten:
    post:
      summary: Создание короткой ссылки
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              format: uri
              example: "https://example.com/very-long-path"
      responses:
        '201':
          description: Успешное создание
          content:
            text/plain:
              schema:
                type: string
                example: "http://localhost:8080/abc123"
        '400':
          description: Невалидный URL или тело запроса
        '500':
          description: Ошибка создания короткого url
  /{code}:
    get:
      summary: Редирект на оригинальный URL
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
            example: "http://localhost:8080/abc123"
      responses:
        '307':
          description: Редирект
          headers:
            Location:
              schema:
                type: string
              example: "https://original.com/long-url"
        '400':
          description: Неверный формат кода
        '404':
          description: Ссылка не найдена
  /api/v1/stats/{code}:
    get:
      summary: Получение статистики кликов по алиасу
      parameters:
        - name: code
          in: path
          required: true
          description: ссылка с алиасом
          schema:
            type: string
            example: "http://localhost:8080/api/v1/stats/abc123"
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/URLStats"
        '404':
          description: Ссылка не найдена
components:
  schemas:
    URLStats:
      type: object
      properties:
        clicks:
          type: integer
          example: 42
        created_at:
          type: string
          format: date-time
          example: "2023-10-01T12:34:56Z"
        original_url:
          type: string
          format: uri
          example: "https://example.com/very-long-path"

